#!/bin/bash
#
# Coverage Gap Analysis Script
# Analyzes JaCoCo reports and identifies missing coverage
#
# Usage: ./coverage-gap-analysis.sh <service-path>
#

set -e

SERVICE_PATH="${1}"
OUTPUT_DIR="$(dirname "$0")/../reports"
mkdir -p "$OUTPUT_DIR"

if [[ -z "$SERVICE_PATH" ]]; then
  echo "Usage: $0 <service-path>"
  exit 1
fi

if [[ ! -d "$SERVICE_PATH" ]]; then
  echo "Error: Service path not found: $SERVICE_PATH"
  exit 1
fi

SERVICE_NAME=$(basename "$SERVICE_PATH")
JACOCO_REPORT="$SERVICE_PATH/target/site/jacoco/index.html"
OUTPUT_FILE="$OUTPUT_DIR/coverage-gap-${SERVICE_NAME}.md"

echo "========================================="
echo "Coverage Gap Analysis"
echo "========================================="
echo "Service: $SERVICE_NAME"
echo "Path: $SERVICE_PATH"
echo ""

# Check if JaCoCo report exists
if [[ ! -f "$JACOCO_REPORT" ]]; then
  echo "⚠️  JaCoCo report not found at: $JACOCO_REPORT"
  echo ""
  echo "Action Required:"
  echo "  1. Run: cd $SERVICE_PATH"
  echo "  2. Run: mvn test jacoco:report"
  echo ""
  exit 0
fi

# Extract coverage from JaCoCo report
echo "Analyzing coverage report..."
echo ""

# Parse JaCoCo HTML report
LINE_COV=$(grep -A 2 "Total" "$JACOCO_REPORT" | grep -oP '\d+%' | head -1 || echo "N/A")
BRANCH_COV=$(grep -A 2 "Total" "$JACOCO_REPORT" | grep -oP '\d+%' | tail -1 || echo "N/A")

# Extract numeric values
LINE_NUM=$(echo "$LINE_COV" | tr -d '%' || echo "0")
BRANCH_NUM=$(echo "$BRANCH_COV" | tr -d '%' || echo "0")

# Determine tier based on service name
if echo "$SERVICE_NAME" | grep -qiE "fraud|security|auth|payment|transaction|settlement|billing|invoice|accounting|ledger|risk|compliance|aml|kyc|audit|policy|governance"; then
  TARGET_LINE=85
  TARGET_BRANCH=75
  TIER="Financial-Grade"
else
  TARGET_LINE=70
  TARGET_BRANCH=60
  TIER="Enterprise-Grade"
fi

# Calculate gaps
LINE_GAP=$((TARGET_LINE - LINE_NUM))
BRANCH_GAP=$((TARGET_BRANCH - BRANCH_NUM))

# Generate report
cat > "$OUTPUT_FILE" << EOMD
# Coverage Gap Analysis: $SERVICE_NAME

**Service**: $SERVICE_NAME
**Tier**: $TIER
**Date**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

---

## Current Coverage

| Metric | Current | Target | Gap | Status |
|--------|---------|--------|-----|--------|
| **Line Coverage** | $LINE_COV | ${TARGET_LINE}% | ${LINE_GAP}% | $( [[ $LINE_NUM -ge $TARGET_LINE ]] && echo "✅ PASS" || echo "❌ FAIL" ) |
| **Branch Coverage** | $BRANCH_COV | ${TARGET_BRANCH}% | ${BRANCH_GAP}% | $( [[ $BRANCH_NUM -ge $TARGET_BRANCH ]] && echo "✅ PASS" || echo "❌ FAIL" ) |

---

## Gap Analysis

$( if [[ $LINE_NUM -lt $TARGET_LINE ]]; then
  echo "### Line Coverage Gap"
  echo ""
  echo "Current line coverage is **${LINE_GAP}% below target**."
  echo ""
  echo "**Required Actions:**"
  echo "- Add tests for uncovered lines"
  echo "- Focus on critical business logic paths"
  echo "- Target: ${LINE_GAP}% more coverage needed"
  echo ""
fi

if [[ $BRANCH_NUM -lt $TARGET_BRANCH ]]; then
  echo "### Branch Coverage Gap"
  echo ""
  echo "Current branch coverage is **${BRANCH_GAP}% below target**."
  echo ""
  echo "**Required Actions:**"
  echo "- Add tests for uncovered conditional branches"
  echo "- Test edge cases and boundary conditions"
  echo "- Target: ${BRANCH_GAP}% more coverage needed"
  echo ""
fi )

if [[ $LINE_NUM -ge $TARGET_LINE ]] && [[ $BRANCH_NUM -ge $TARGET_BRANCH ]]; then
  echo "### ✅ Coverage Targets Met"
  echo ""
  echo "All coverage thresholds satisfied!"
  echo ""
  echo "**Next Steps:**"
  echo "$( if [[ "$TIER" == "Financial-Grade" ]]; then
    echo "- Run mutation tests: mvn pitest:mutationCoverage"
    echo "- Verify 60% mutation score"
  else
    echo "- Service ready for deployment"
  fi )"
  echo ""
fi )

---

## Detailed Findings

To view detailed coverage by package:
\`\`\`bash
cd $SERVICE_PATH
mvn jacoco:report
open target/site/jacoco/index.html
\`\`\`

---

## Recommended Actions

$( if [[ $LINE_NUM -lt $TARGET_LINE ]] || [[ $BRANCH_NUM -lt $TARGET_BRANCH ]]; then
  echo "1. Run test generation script:"
  echo "   \`\`\`"
  echo "   ./scripts/generate-missing-tests.sh $SERVICE_PATH"
  echo "   \`\`\`"
  echo ""
  echo "2. Run tests with coverage:"
  echo "   \`\`\`"
  echo "   cd $SERVICE_PATH"
  echo "   mvn verify -Pci"
  echo "   \`\`\`"
  echo ""
  echo "3. Verify coverage thresholds:"
  echo "   \`\`\`"
  echo "   mvn jacoco:check"
  echo "   \`\`\`"
else
  echo "✅ Service meets all coverage requirements"
  echo ""
  echo "$( if [[ "$TIER" == "Financial-Grade" ]]; then
    echo "Financial-Grade Next Steps:"
    echo "- Run mutation testing"
    echo "- Run architecture tests"
    echo "- Run security tests"
    echo "- Run SLO/observability tests"
  fi )"
fi )

---

**Generated by**: coverage-gap-analysis.sh
EOMD

echo "Coverage Summary:"
echo "  Line:    $LINE_COV (target: ${TARGET_LINE}%)"
echo "  Branch:  $BRANCH_COV (target: ${TARGET_BRANCH}%)"
echo ""

if [[ $LINE_NUM -ge $TARGET_LINE ]] && [[ $BRANCH_NUM -ge $TARGET_BRANCH ]]; then
  echo "✅ Coverage targets met!"
elif [[ $LINE_NUM -lt $TARGET_LINE ]] || [[ $BRANCH_NUM -lt $TARGET_BRANCH ]]; then
  echo "❌ Coverage below target"
  echo ""
  echo "Gap to fill:"
  echo "  Line:    ${LINE_GAP}% needed"
  echo "  Branch:  ${BRANCH_GAP}% needed"
fi

echo ""
echo "Report saved to: $OUTPUT_FILE"
echo "========================================="
